# Generated by Django 4.0.4 on 2022-05-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=45)),
                ('birth', models.DateField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=30)),
                ('terms_agreements', models.JSONField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
